export const userElements = {
    addButton: '.oxd-button-icon',
    userRoleDropdown: '.oxd-select-text',
    userRoleAndStatusOption: '.oxd-select-dropdown',
    userStatusDropdown: '.oxd-select-text',
    employeeNameInput: '.oxd-autocomplete-wrapper',
    employeeOption: '.oxd-autocomplete-option',
    usernameInput: '.oxd-input--active',
    passwordInput: '[type="password"]',
    saveButton: '.orangehrm-left-space',
    edDeButton: '.oxd-table-cell-action-space',
    noYesDelete: '.orangehrm-button-margin',
    table: '.oxd-table',
    tableBody: '.oxd-table-body',
    tableRow: '.oxd-table-row',
    tableCell: 'div[role="cell"]',
    changePasswordBox: '.oxd-checkbox-input-icon',
    usernameContanier: '.oxd-grid-item--gutters',
}
